# Generated by Django 2.1.2 on 2018-10-29 15:38

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cor', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('prioridade', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Icone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_file', models.FileField(upload_to='icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('visivel', models.BooleanField(default=True)),
                ('fonte_dados', models.TextField(blank=True, null=True)),
                ('tabela_pg', models.CharField(blank=True, max_length=255, null=True)),
                ('tabela_drive', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitulo', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('url_tableau', models.CharField(blank=True, max_length=255, null=True)),
                ('prioridade', models.IntegerField(default=1)),
                ('dados_craai', models.BooleanField(default=True)),
                ('dados_estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area_mae', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temas', to='mpplus_rest.Area')),
                ('areas_correlatas', models.ManyToManyField(blank=True, related_name='temas_correlatos', to='mpplus_rest.Area')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='icone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mpplus_rest.Icone'),
        ),
    ]
