# Generated by Django 2.1.2 on 2018-10-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpplus_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Areas',
            new_name='Area',
        ),
        migrations.RenameModel(
            old_name='Icones',
            new_name='Icone',
        ),
    ]
