# Generated by Django 2.1.7 on 2019-03-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpplus_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icone',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
