# Generated by Django 2.1.7 on 2019-03-14 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpplus_rest', '0002_icone_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icone',
            name='data_file',
        ),
    ]
