# Generated by Django 2.1.2 on 2018-10-05 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpplus_rest', '0005_auto_20181005_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area_mae', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mpplus_rest.Area')),
            ],
        ),
        migrations.RemoveField(
            model_name='icone',
            name='file_name',
        ),
    ]
