# Generated by Django 2.1.2 on 2018-10-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpplus_rest', '0006_auto_20181005_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tema',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='tema',
            name='ocultar',
            field=models.BooleanField(default=False),
        ),
    ]
