# Generated by Django 2.1.2 on 2018-10-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpplus_rest', '0007_auto_20181005_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema',
            name='ocultar',
        ),
        migrations.AddField(
            model_name='tema',
            name='dados_craai',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tema',
            name='dados_estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tema',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tema',
            name='fonte_dados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tema',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tema',
            name='prioridade',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tema',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tema',
            name='tabela_drive',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tema',
            name='tabela_pg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tema',
            name='url_tableau',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tema',
            name='visivel',
            field=models.BooleanField(default=True),
        ),
    ]
