# Generated by Django 2.1.2 on 2018-10-05 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpplus_rest', '0008_auto_20181005_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='areas_correlatas',
            field=models.ManyToManyField(related_name='areas_correlatas', to='mpplus_rest.Area'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='area_mae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='area_mae', to='mpplus_rest.Area'),
        ),
    ]
