# Generated by Django 2.1.2 on 2018-10-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpplus_rest', '0010_auto_20181005_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='areas_correlatas',
            field=models.ManyToManyField(blank=True, related_name='temas_correlatos', to='mpplus_rest.Area'),
        ),
    ]
